name: Build Stride Docs - Staging - GitHub
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'wiki/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: windows-latest
    steps:
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: stride-docs
    - name: Checkout Stride
      uses: actions/checkout@v3
      with:
        repository: stride3d/stride
        token: ${{ secrets.GITHUB_TOKEN }}
        path: stride
    - name: Copy global.json file
      run: xcopy stride-docs\global.json . /Y
    - name: Check the content of the folder
      run: |
        echo "Content of folder:"
        ls -la
    - run: dotnet tool update -g docfx
#    - run: dotnet tool install -g docfx --version 2.65.1
    - run: docfx stride-docs/en/docfx.json
#      continue-on-error: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: stride-docs/en/_site
