name: Paths check
on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Stride
      uses: actions/checkout@v3
      with:
        repository: stride3d/stride
        token: ${{ secrets.GITHUB_TOKEN }}    
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check the content of the folder
      run: |
        echo "Content of folder:"
        ls -la
    - name: Check the content of the parent folder
      run: |
        echo "Content of the parent folder:"
        ls -la ..        
