name: Paths check
on:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: windows-2022
    steps:
      - name: Check .NET Framework version
        run: |
          reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP" /s | findstr /i version
